Arch:
  name: resnet50
  num_channel: 1
  output_k_A: 70
  output_k_B: 10
  num_sub_heads: 1
  semisup: False

Optim:
  name: Adam
  lr: 0.0001

Scheduler:
  name: MultiStepLR
  milestones: [100, 200, 300, 400, 500, 600, 700, 800, 900]
  gamma: 0.75

DataLoader:
  batch_size: 200
  shuffle: true
  num_workers: 16

Trainer:
  max_epoch: 1000
  save_dir: multihead_cifar
  device: cuda
  head_control_params:
    B: 1
  use_sobel: false

