Arch:
  name: clusternet6cTwoHead
  input_size: 24
  num_channel: 1
  output_k_A: 50
  output_k_B: 10
  num_sub_heads: 1
  semisup: False

Optim:
  name: Adam
  lr: 0.002

Scheduler:
  name: MultiStepLR
  milestones: [100, 200, 300, 400, 500, 600, 700, 800, 900]
  gamma: 0.75

DataLoader:
  batch_size: 150
  shuffle: true
  num_workers: 16
  transforms: naive

Trainer:
  name: imsatvat
  max_epoch: 2
  save_dir: multihead_mnist
  device: cuda:0
  head_control_params:
    A: 0
    B: 1
  VAT_params:
    eps: 10.0

# for mnist dataset, imsat vat trainer VAT_params. eps should be greater than 10.
Seed:
  0